### ISSUE TITLE
MyAccount component is not finding "store"

### ISSUE THREAD

**Issue by andreamalin** [Cleeng/mediastore-sdk#21]
After adding the Provider component in index.jsx above my App component using store provided by cleeng sdk, MyAccount component is still not working.
Is there any other step I am missing? Thanks

index.jsx
![image](https://user-images.githubusercontent.com/28350445/164576559-ae19f1ef-48c2-4f77-aa0a-3ac6eeddecaf.png)

Error displayed
![image](https://user-images.githubusercontent.com/28350445/164576419-7d0b6cc2-d371-4548-a24d-2e5e03466711.png)

**Comment by yinglingbryan** [comment]
@andreamalin how did you resolve this?  I am having the same issue on my end

**Comment by andreamalin** [comment]
> @andreamalin how did you resolve this? I am having the same issue on my end

I ended up creating my own store using redux. 
Here is a code snippet, let me know if you have more questions:
``` store/index.js
export const store = configureStore({
  reducer: persistReducer(persistConfig, rootReducer),
  middleware: (getDefaultMiddleware) => getDefaultMiddleware({
    serializableCheck: {
      ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER],
    },
  }),
})
```

entry point
```
import { store } from './store/index'
import App from './App'

const root = (
    <Provider store={store}>
        <Router>
          <App />
        </Router>
    </Provider>
)
```
