### ISSUE TITLE
Bundled SDK not taking theme into account at first load

### ISSUE THREAD

**Issue by julien-tanguy-wiztivi** [Cleeng/mediastore-sdk#70]
This issue occures when SDK is fully bundled in one file for web.

Steps to reproduce :
- Set theme with `Config.setTheme` at app startup
- Open a MS SDK component, newly set theme is not applied (but theme is well stored in local storage)
- Reload app and open a MS SDK component, theme is well applied

It seems it comes from below lines :
https://github.com/Cleeng/mediastore-sdk/blob/c3396634b46774a4ed97f3199ace74925cb2dd5b/src/styles/variables.js#L4

In fully bundled SDK, all theme consts are initialized at bundle js file load when page is loaded, then it's to late doing it with `Config.setTheme` as we have to first load the whole library.

We were able to work around this problem, by first storing theme on our own by calling directly `localstorage` with the right key and then loading the whole SDK bundled js file.

**Comment by pawelacio** [comment]
The described issue is connected with the availability of the `CLEENG_THEME` entry in the local storage. It looks that you are rendering the **mediastore-sdk** component before the local storage is updated with the new value that you passed with the `Config.setTheme` method. 

To avoid such behavior we recommend you to call that method up to the application root or outside the React component. In that case all the configuration will be updated with the correct value before any component will be rendered.  A good place to do it would be the `index.js` file which is the application's root, for example.

When it comes to your workaround it's also a good way to solve it on your side and won't have a bad influence on the usage of the **mediastore-sdk** components so it is on your side if you want to change it to the solution that we described.
